### ISSUE TITLE
Create and complete ProfileFragment

### ISSUE THREAD

**Issue by juanmarquez70** [TBean18/COP4655TeamApp#22]
# Task List
- [x] #10

**Comment by juanmarquez70** [comment]
Its been created and should be constructed as we were taught before, review guides

**Comment by juancho2124** [comment]
In the ProfileFragment, the user should be able to schedule desired time for qoute.

**Comment by TBean18** [comment]
Added Logout Button to Profile fragment #28

**Comment by juancho2124** [comment]
Added Styles and Schedule buttons to ProfileFragment. Working on opening new activities when clicked on.
